version: '3.8'

services:
  backend:
    build: ./chatbox-api
    ports:
      - "8000:8000"
    volumes:
      - ./chatbox-api:/app
    env_file:
      - chatbox-api/.env
    environment:
      - PYTHONPATH=/app
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - DATABASE_URL=postgresql://app_user:app_password@db:5432/app_db
      - VECTOR_DB_URL=postgresql://app_user:app_password@vectordb:5432/app_db
    depends_on:
      - db
    networks:
      - chatbox_gpt

  frontend:
    build: ./chatbox-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - chatbox_gpt

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    networks:
      - chatbox_gpt

  vectordb:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "6024:5432"
    networks:
      - chatbox_gpt

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - chatbox_gpt

networks:
  chatbox_gpt:
    driver: bridge
