FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy package*.json and package-lock.json (if available) to the working directory
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the application will run (if applicable)
EXPOSE 3000 

# Define the command to start the application
CMD ["npm", "start"] 
